services:
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  rails:
    build:
      context: ./rails
      dockerfile: Dockerfile
    # command: bash -c "bundle exec rails s -b '0.0.0.0'"
    command: bash -c "tail -f log/development.log"
    volumes:
      - ./rails:/app
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true

volumes:
  mysql-data:
