source "https://rubygems.org"
git_source(:github) {|repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

# railsの起動時間を短縮する（標準gem）
gem "bootsnap", require: false

# MySQLに接続する
gem "mysql2", "~> 0.5"

# cors設定を管理する
gem "rack-cors"

# ユーザー認証を提供
gem "devise"

# devise を日本語化
gem "devise-i18n"

# ユーザーのトークン認証を提供
gem "devise_token_auth"

# pumaサーバーを使えるようにする（標準gem）
gem "puma", "~> 5.0"

# rails本体（標準gem）
gem "rails", "~> 7.0.4"

# タイムゾーン情報を提供する（標準gem）
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

# 開発環境でメール送信をテスト
gem "letter_opener_web"

# レスポンスJSONを制御する
gem "active_model_serializers"

# メッセージを日本語化
gem "rails-i18n"

# ページネーション機能を提供する
gem "kaminari"

# N+1発生時にアラートを表示する
gem "bullet"

group :development, :test do
  # テスト用データを作成する
  gem "factory_bot_rails"
  gem "faker"

  # 開発環境でメール送信をテストする
  gem "letter_opener_web"

  # pry コンソールを使えるようにする。
  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rails"

  gem "rspec-rails"

  gem "rubocop-faker"
  gem "rubocop-rails"
  gem "rubocop-rspec"
end
